<#
.SYNOPSIS
  Builds FRENCH_REVIEW.md from the shipped Keyed and DefInjected XML, for TRANSLATIONS.md's
  "Systematic French review by Virginie" (2026-09-30).
.DESCRIPTION
  Reads every Mod/Languages/French/{Keyed,DefInjected}/**/*.xml key and its English counterpart
  at the same relative path. Housebroken has no source language other than English (it was
  written in English from the start, not ported), so Original = English for every row; this is
  stated once at the top rather than repeated per row. Adapted from FoodCourt's
  _tools/Generate-FrenchReview.ps1 for a mod with no Defs-based English fallback to resolve.
#>
param(
    [string]$Root = (Split-Path $PSScriptRoot -Parent),
    [string]$OutFile = (Join-Path (Split-Path $PSScriptRoot -Parent) 'FRENCH_REVIEW.md')
)

function Get-Entries($path) {
    $entries = [ordered]@{}
    if (-not (Test-Path $path)) { return $entries }
    $xml = [xml](Get-Content $path -Raw -Encoding UTF8)
    foreach ($node in $xml.LanguageData.ChildNodes) {
        if ($node.NodeType -ne 'Element') { continue }
        $entries[$node.Name] = $node.InnerText
    }
    return $entries
}

# DefInjected keys with no English override fall back to the Def's own field (the game's native
# fallback), exactly as TRANSLATIONS.md describes: "English may be supplied by the original
# English Def value". Housebroken has exactly one such file (MainButtonDef), read directly.
function Resolve-DefField($defsRoot, [string]$key) {
    $parts = $key -split '\.'
    $defName = $parts[0]
    $field = $parts[1]
    foreach ($f in (Get-ChildItem $defsRoot -Recurse -Filter *.xml)) {
        $x = [xml](Get-Content $f.FullName -Raw -Encoding UTF8)
        $node = $x.SelectSingleNode("//*[defName='$defName']")
        if ($node -and $node.$field) { return [string]$node.$field }
    }
    return $null
}

$frenchRoot = Join-Path $Root 'Mod/Languages/French'
$englishRoot = Join-Path $Root 'Mod/Languages/English'
$defsRoot = Join-Path $Root 'Mod/Defs'

$frenchFiles = Get-ChildItem $frenchRoot -Recurse -Filter *.xml | Sort-Object FullName
$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine("# French review")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated by ``_tools/Generate-FrenchReview.ps1`` for TRANSLATIONS.md's systematic French review.")
[void]$out.AppendLine("**Original column: same as English throughout.** Housebroken was written in English from the")
[void]$out.AppendLine("start; it is not a port, and no other source-language text exists anywhere in this repository.")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated $(Get-Date -Format 'yyyy-MM-dd'), revision: $(git -C $Root rev-parse --short HEAD 2>$null).")
[void]$out.AppendLine()
[void]$out.AppendLine("**No text in this mod agrees with a pawn's gender.** Every French string here is either an")
[void]$out.AppendLine("impersonal settings label, a stat-explanation line about ``l'animal`` (grammatically masculine")
[void]$out.AppendLine("as a common noun, not a PAWN_gender agreement), or the MainButtons shortcut label. No")
[void]$out.AppendLine("``{PAWN_gender ? ... }`` switch, letter, message or thought text exists to review against the")
[void]$out.AppendLine("2026-09-30 gender-agreement rule; none is flagged below for that reason.")
[void]$out.AppendLine()

foreach ($ff in $frenchFiles) {
    $rel = $ff.FullName.Substring($frenchRoot.Length + 1) -replace '\\', '/'
    $frEntries = Get-Entries $ff.FullName
    if ($frEntries.Count -eq 0) { continue }

    $enPath = Join-Path $englishRoot $rel
    $enEntries = Get-Entries $enPath

    [void]$out.AppendLine("## $rel")
    [void]$out.AppendLine()
    [void]$out.AppendLine("| Key or path | Original | English | French |")
    [void]$out.AppendLine("|---|---|---|---|")
    foreach ($key in $frEntries.Keys) {
        $fr = $frEntries[$key]
        $en = if ($enEntries.Contains($key)) { $enEntries[$key] } else { Resolve-DefField $defsRoot $key }
        $flag = if ($null -eq $en) { ' | ? | no matching English key or Def field' } else { '' }
        if ($null -eq $en) { $en = '*(not found, check by hand)*' }
        $origCell = ($en -replace '\|', '\|') -replace "`n", ' '
        $enCell = ($en -replace '\|', '\|') -replace "`n", ' '
        $frCell = ($fr -replace '\|', '\|') -replace "`n", ' '
        $keyCell = $key -replace '\|', '\|'
        [void]$out.AppendLine("| $keyCell | $origCell | $enCell | $frCell$flag |")
    }
    [void]$out.AppendLine()
}

[System.IO.File]::WriteAllText($OutFile, $out.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Output "wrote $OutFile"
